name: Run Calendar Bot Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  Run-Calendar-Bot-Tests:
    name: Run Calendar Bot Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Create dummy .env for tests
        run: |
          echo "DISCORD_BOT_TOKEN=dummy_token" >> .env
          echo "DISCORD_GUILD_ID=123456789012345678" >> .env
          echo "ICAL_URL=https://example.com/calendar.ics" >> .env

      - name: Run tests
        run: PYTHONPATH=. pytest
